services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./node_modules:/var/www/html/node_modules
        networks:
            - laravel_network
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        command: >
            sh -c "
            until mysqladmin ping -h db --silent; do
                echo 'Waiting for database...';
                sleep 2;
            done &&
            chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
            chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
            composer install &&
            php artisan key:generate &&
            php artisan migrate:refresh --force &&
            php artisan db:seed --force &&
            php-fpm
            "
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network
    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    dbdata:
